name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]
        poetry-version: [1.2.0]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install System Dependencies (macOS)
        if: matrix.os == 'macOS-latest'
        run: |
          brew install pkg-config
          brew install libffi
          brew install cairo
          brew install pango
          brew install gdal
      - name: Install System Dependencies (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install gdal-bin libgdal-dev
      # Print the gdal version, so we know what the minimum version we can
      # support in pyproject.toml. Unlike homebrew for macOS, ubuntugis for
      # Ubuntu seems to be a bit behind the latest version by a few months.
      - name: GDAL version info (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          gdal-config --version
      - name: Install dependencies
        run: |
          poetry install
      - name: Run linting
        run: |
          poetry run flake8
      - name: Run tests
        run: |
          poetry run pytest
